import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id("org.jetbrains.dokka") version "1.8.20"
    id 'maven-publish'
    id 'com.google.devtools.ksp'
    id 'signing'
    id 'kotlin-parcelize'
}

apply from: '../scripts/version.gradle'

ext {
    PUBLISH_GROUP_ID = "net.ballmerlabs.scatterbrainsdk"
    PUBLISH_VERSION = projectVersionName
    PUBLISH_ARTIFACT_ID = "sdk"
    projectVersionName = ext['projectVersionName']
}

android {
    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 35
        compileSdk 35
        versionCode 1
        versionName = version

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        //consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            //proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.15"
    }

    lintOptions {
        abortOnError false
        disable "JvmStaticProvidesInObjectDetector", "FieldSiteTargetOnQualifierAnnotation", "ModuleCompanionObjects", "ModuleCompanionObjectsNotInModuleParent"
    }

    namespace 'net.ballmerlabs.scatterbrainsdk'

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17
        freeCompilerArgs = [
                "-Xstring-concat=inline"
        ]
    }
    compileSdk 34
    buildFeatures {
        aidl true
    }
}

apply from: "../gradle/jacoco.gradle"

dependencies {

    implementation 'androidx.appcompat:appcompat:1.7.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    implementation "androidx.core:core-ktx:1.13.1"
    implementation 'com.google.dagger:dagger:2.51.1'
    ksp 'com.google.dagger:dagger-compiler:2.51.1'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.8.3'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3'
    implementation "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.7"
    implementation "androidx.compose.runtime:runtime:1.6.8"
    ksp "org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.5.0"
}

repositories {
    mavenCentral()
    google()
    maven { url "https://jitpack.io" }
    gradlePluginPortal()
}

tasks.withType(KotlinCompile).configureEach {
    compilerOptions.freeCompilerArgs.addAll(
            "-P",
            "plugin:androidx.compose.compiler.plugins.kotlin:reportsDestination=/Users/khanson/Documents/repos/scatter/",
    )
}

if (rootProject.hasProperty("publishable")) {
    apply from: "../scripts/publish-module.gradle"
}

