import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id("org.jetbrains.dokka") version "2.1.0"
    id 'maven-publish'
    id 'com.google.devtools.ksp'
    id 'signing'
    id 'kotlin-parcelize'
    id 'org.jetbrains.kotlin.plugin.compose' version "2.3.0"
}

apply from: '../scripts/version.gradle'

ext {
    PUBLISH_GROUP_ID = "net.ballmerlabs.scatterbrainsdk"
    PUBLISH_VERSION = projectVersionName
    PUBLISH_ARTIFACT_ID = "sdk"
    projectVersionName = ext['projectVersionName']
}

composeCompiler {
    reportsDestination = layout.buildDirectory.dir("compose_compiler")
    metricsDestination = layout.buildDirectory.dir("compose_compiler")
}


android {
    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 36
        compileSdk 36
        versionCode 1
        versionName = version

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        //consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            //proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    buildFeatures {
        compose = true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.15"
    }

    lintOptions {
        abortOnError false
        disable "JvmStaticProvidesInObjectDetector", "FieldSiteTargetOnQualifierAnnotation", "ModuleCompanionObjects", "ModuleCompanionObjectsNotInModuleParent"
    }

    namespace 'net.ballmerlabs.scatterbrainsdk'

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_21
        freeCompilerArgs = [
                "-Xstring-concat=inline"
        ]
    }
    compileSdk 36
    buildFeatures {
        aidl true
    }

    packagingOptions {
        exclude 'lib/x86/libsqlite3x.so'
        exclude 'lib/armeabi-v7a/libsqlite3x.so'
    }
}

//apply from: "../gradle/jacoco.gradle"

dependencies {

    implementation libs.appcompat
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation libs.core.ktx
    implementation libs.dagger
    ksp libs.dagger.compiler
    implementation libs.lifecycle.livedata.ktx
    implementation libs.kotlin.stdlib.jdk7
    implementation libs.kotlin.stdlib
    implementation libs.jetbrains.kotlinx.coroutines.core
    implementation libs.kotlinx.collections.immutable
    implementation libs.androidx.runtime
}

repositories {
    mavenCentral()
    google()
    maven { url "https://jitpack.io" }
    gradlePluginPortal()
}

if (rootProject.hasProperty("publishable")) {
    apply from: "../scripts/publish-module.gradle"
}

